CREATE CONSTRAINT actor_id IF NOT EXISTS FOR (a:Actor) REQUIRE a.actor_id IS UNIQUE;
CREATE CONSTRAINT handle_id IF NOT EXISTS FOR (h:Handle) REQUIRE h.handle_id IS UNIQUE;
CREATE CONSTRAINT wallet_addr IF NOT EXISTS FOR (w:Wallet) REQUIRE (w.address, w.currency) IS UNIQUE;
CREATE CONSTRAINT onion_addr IF NOT EXISTS FOR (o:OnionService) REQUIRE o.onion_address IS UNIQUE;
CREATE CONSTRAINT clearnet_ip IF NOT EXISTS FOR (c:ClearnetIP) REQUIRE c.ip_address IS UNIQUE;
CREATE CONSTRAINT pgp_fp IF NOT EXISTS FOR (p:PGPKey) REQUIRE p.fingerprint IS UNIQUE;
CREATE CONSTRAINT vasp_name IF NOT EXISTS FOR (v:VASP) REQUIRE v.name IS UNIQUE;
